t1 = 0
t2 = 1
cont = 3
n = int(input('Quantos termos da sequência de Fibonnaci você quer saber? '))
print('{} - {}'.format(t1, t2),end='')
while cont <= n:
    cont += 1
    t3 = t2 + t1
    print(' - {}'.format(t3),end='')
    t1 = t2
    t2 = t3
print(' - FIM',end='')